services:
  dead-mans-switch:
    container_name: circa10a/dead-mans-switch
    image: circa10a/dead-mans-switch
    command: server --data-dir=/data
    ports:
      - 8080:8080
    volumes:
      - dms_data:/data

volumes:
  dms_data:
