---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dead-mans-switch
spec:
  selector:
    matchLabels:
      app: dead-mans-switch
  replicas: 1
  template:
    metadata:
      labels:
        app: dead-mans-switch
    spec:
      containers:
      - name: dead-mans-switch
        image: circa10a/dead-mans-switch
        command: ["dead-mans-switch"]
        args: ["server", "--storage-dir", "/data"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dead-mans-switch-pvc
