---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dead-mans-switch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dead-mans-switch
spec:
  selector:
    matchLabels:
      app: dead-mans-switch
  replicas: 1
  template:
    metadata:
      labels:
        app: dead-mans-switch
    spec:
      containers:
      - name: dead-mans-switch
        image: circa10a/dead-mans-switch
        args: ["server", "--data-dir", "/data", "--port", "8080"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dead-mans-switch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dead-mans-switch
  labels:
    app: dead-mans-switch
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: dead-mans-switch
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dead-mans-switch
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dead-mans-switch
